const landrinaSolid = 'LondrinaSolid';
const navBarIcons = [
  {
    'icon': 'assets/svgs/navigationBar/home.svg',
    'activeIcon': 'assets/svgs/navigationBar/homeActive.svg',
    'label': 'Нүүр',
  },
  {
    'icon': 'assets/svgs/navigationBar/emergency.svg',
    'activeIcon': 'assets/svgs/navigationBar/emergencyActive.svg',
    'label': 'Яаралтай',
  },
  {
    'icon': 'assets/svgs/navigationBar/notary.svg',
    'activeIcon': 'assets/svgs/navigationBar/notaryActive.svg',
    'label': 'Нотариат',
  },
  {
    'icon': 'assets/svgs/navigationBar/podcast.svg',
    'activeIcon': 'assets/svgs/navigationBar/podcastActive.svg',
    'label': 'Подкаст',
  },
];

final registerSymbols = [
  "А",
  "Б",
  "В",
  "Г",
  "Д",
  "Е",
  "Ё",
  "Ж",
  "З",
  "И",
  "Й",
  "К",
  "Л",
  "М",
  "Н",
  "О",
  "Ө",
  "П",
  "Р",
  "С",
  "Т",
  "У",
  "Ү",
  "Ф",
  "Х",
  "Ц",
  "Ч",
  "Ш",
  "Щ",
  "Ъ",
  "Ь",
  "Ы",
  "Э",
  "Ю",
  "Я",
];
